apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- workflow-controller
- argo-ui
- argo-server
images:
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: latest
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: latest
