apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crds
- workflow-controller
- argo-server
images:
- name: argoproj/argo-server
  newName: argoproj/argo-server
  newTag: apiserverimpl
- name: argoproj/argoui
  newName: argoproj/argoui
  newTag: apiserverimpl
- name: argoproj/workflow-controller
  newName: argoproj/workflow-controller
  newTag: apiserverimpl
