apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  template:
    spec:
      containers:
        - name: argo-server
          env:
            # TODO - maybe unused
            - name: FORCE_NAMESPACE_ISOLATION
              value: "true"
