apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base
- ./argo-server-rbac
- ./workflow-controller-rbac

patchesStrategicMerge:
- ./overlays/argo-server-deployment.yaml
- ./overlays/workflow-controller-configmap.yaml
- ./overlays/workflow-controller-deployment.yaml
