apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-server
spec:
  selector:
    matchLabels:
      app: argo-server
  template:
    metadata:
      labels:
        app: argo-server
    spec:
      # TODO we need to have a separate service account with
      # - read the config map
      # - read the secret
      # - read/write/delete workflows
      # - read/write/delete cron workflows
      # - read/write/delete workflow templates
      serviceAccountName: argo-server
      containers:
        - name: argo-server
          image: argoproj/argo-server:latest
          args: [--auth-type, client]
          ports:
            - containerPort: 2746
          readinessProbe:
            httpGet:
              port: 2746
              scheme: HTTP
              path: /
